-- DualRep starter library, part 7 of 7 (for the Supabase SQL Editor).
-- GENERATED by scripts/library/starter-library-sql.mjs; do not edit. Paste the whole part and click Run.
-- Run all 7 parts, in any order. Running a part again is safe: it rewrites the same rows.
insert into public.exercises (
  id, name, muscle_group, secondary_muscles, body_region, category, dataset_category, equipment,
  location, movement_pattern, demand_level, level, force, mechanic, micro_ok, instructions, images,
  origin, dataset_id, reviewed, owner_id, group_id
) values
  ('00000000-0000-4000-8000-0000000e0057', 'EZ-bar curl', 'biceps', '["forearms"]', 'upper',
   'strength', null, '["ez_bar"]', 'gym', 'other', 1, 'beginner', 'pull', 'isolation', true,
   '["Hold an EZ bar on the angled grips with your arms straight.",
    "Keep your elbows at your sides and curl the bar toward your shoulders.",
    "Lower it slowly without swinging."]',
   '[]', 'interverse', null, true, null, null),
  ('00000000-0000-4000-8000-0000000e0058', 'Rower intervals', 'quadriceps',
   '["middle back","lats","hamstrings"]', 'cardio', 'conditioning', null, '["cardio_machine"]',
   'gym', 'conditioning', 2, 'beginner', null, 'compound', true,
   '["Strap your feet in and sit tall holding the handle with straight arms.",
    "Push with your legs first, then lean back slightly and pull the handle to your lower ribs.",
    "Return arms, body, then legs. Row hard for the work time and easy in between."]',
   '[]', 'interverse', null, true, null, null),
  ('00000000-0000-4000-8000-0000000e0059', 'Bike intervals', 'quadriceps',
   '["hamstrings","glutes","calves"]', 'cardio', 'conditioning', null, '["cardio_machine"]', 'gym',
   'conditioning', 2, 'beginner', null, 'compound', true,
   '["Set the seat so your knee stays slightly bent at the bottom of each pedal stroke.",
    "Pedal hard for the work time at a resistance you can keep up.",
    "Ease off and pedal lightly to recover between efforts."]',
   '[]', 'interverse', null, true, null, null),
  ('00000000-0000-4000-8000-0000000e005a', 'Treadmill intervals', 'quadriceps',
   '["hamstrings","calves"]', 'cardio', 'conditioning', null, '["cardio_machine"]', 'gym',
   'conditioning', 2, 'beginner', null, 'compound', false,
   '["Clip on the safety key and start at an easy walk.",
    "Raise the speed or incline to a brisk walk or run for the work time.",
    "Lower it back to an easy pace to recover. Slow the belt right down before stepping off."]',
   '[]', 'interverse', null, true, null, null)
on conflict (id) do update set
  name = excluded.name, muscle_group = excluded.muscle_group,
  secondary_muscles = excluded.secondary_muscles, body_region = excluded.body_region,
  category = excluded.category, dataset_category = excluded.dataset_category,
  equipment = excluded.equipment, location = excluded.location,
  movement_pattern = excluded.movement_pattern, demand_level = excluded.demand_level,
  level = excluded.level, force = excluded.force, mechanic = excluded.mechanic,
  micro_ok = excluded.micro_ok, instructions = excluded.instructions, images = excluded.images,
  origin = excluded.origin, dataset_id = excluded.dataset_id, reviewed = excluded.reviewed,
  owner_id = excluded.owner_id, group_id = excluded.group_id;
